# Generated by Django 3.2.7 on 2021-09-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author'),
    ]

    operations = [
    ]
